version: '3.8'

services:
  snmpd:
    build:
      context: ./snmpd
      dockerfile: Dockerfile
    container_name: snmpd
    ports:
      - "161:161/udp"
      - "162:162/udp"
    networks:
      - edge-network
    healthcheck:
      test: ["CMD", "snmpget", "-v2c", "-c", "public", "localhost:161", "1.3.6.1.2.1.1.5.0"]
      interval: 30s
      timeout: 10s
      retries: 3

  edge-agent:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    container_name: edge-agent
    ports:
      - "9082:9081"
    depends_on:
      snmpd:
        condition: service_healthy
    networks:
      - edge-network
    environment:
      - SNMP_HOST=snmpd
      - SNMP_PORT=161
      - SNMP_COMMUNITY=public
    volumes:
      - ./config:/app/config
      - ${PWD:-.}:/app  # Source code mounted for development

networks:
  edge-network:
    name: edge-network
