version: '3.8'

name: edge-agent-services-dev

services:
  edge-agent:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: edge-agent-dev
    command: tail -f /dev/null
    tty: true
    stdin_open: true
    ports:
      - "9080:9080"
    networks:
      - edge-network
    volumes:
      - .:/app
    environment:
      - SNMP_HOST=snmpd
      - SNMP_PORT=161
      - SNMP_COMMUNITY=public
    depends_on:
      snmpd:
        condition: service_healthy

  snmpd:
    extends:
      file: docker-compose.yml
      service: snmpd

networks:
  edge-network:
