version: '3'

name: edge-agent-services-dev

services:
  edge-agent:
    image: edge-agent-dev
    container_name: edge-agent-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "9080:9080"
    volumes:
      - .:/app
    restart: always
    environment:
      - SNMP_HOST=snmpd
      - SNMP_PORT=161
      - SNMP_COMMUNITY=public
    command: sh -c "cd /app && rm -rf build && mkdir -p build && cd build && cmake .. && make && ./edge-agent"
    depends_on:
      - snmpd

  snmpd:
    build:
      context: ./snmpd
      dockerfile: Dockerfile
    container_name: snmpd-dev
    ports:
      - "161:161/udp"
    restart: always
